"""init database

Revision ID: 40a51d118d42
Revises: 
Create Date: 2019-07-22 02:29:18.685488

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '40a51d118d42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_seeder',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('is_multi_access', sa.Boolean(), nullable=False),
                    sa.Column('opened_time', sa.Time(), nullable=False),
                    sa.Column('closed_time', sa.Time(), nullable=False),
                    sa.Column('address', sa.String(length=500), nullable=False),
                    sa.Column('google_map_id', sa.String(length=50), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('google_map_id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('role',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('role_type', sa.String(length=50), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('email', sa.String(length=50), nullable=False),
                    sa.Column('refresh_token', sa.String(length=100), nullable=False),
                    sa.Column('avatar_url', sa.String(length=200), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('meeting',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('description', sa.String(length=500), nullable=False),
                    sa.Column('creator_id', sa.Integer(), nullable=False),
                    sa.Column('is_periodic', sa.Boolean(), nullable=False),
                    sa.Column('state', sa.Boolean(), nullable=False),
                    sa.Column('location_id', sa.Integer(), nullable=False),
                    sa.Column('started_time', sa.DateTime(), nullable=False),
                    sa.Column('finished_time', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['location_id'], ['location_seeder.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('meeting_user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('meeting_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('is_accepted', sa.Boolean(), nullable=False),
                    sa.Column('is_coordinator', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_user')
    op.drop_table('meeting')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('location_seeder')
    # ### end Alembic commands ###
