export default {
  LOGIN: '/api/login_code',
  GET_ALL_MEETING: '/api/meeting/all',
  LIST_ROOM: '/api/location/all',
  GET_EMPTY_LOCATIONS: '/api/meeting/check',
  POST_MEETING: '/api/meeting/post',
  POST_MEETING_BY_ADMIN: '/api/meeting/admin/post',
  GET_USERS: '/api/user/suggest',
  GET_MEETING: '/api/meeting/get',
  PATCH_MEETING: '/api/meeting/patch',
  PATCH_MEETING_BY_ADMIN: '/api/meeting/admin/patch',
  PATCH_MEETING_PERIODIC: '/api/meeting/periodic/patch',
  PATCH_MEETING_PERIODIC_BY_ADMIN: '/api/meeting/admin/periodic/patch',
  POST_CONFIRM: '/api/user/confirm',
  PATCH_CHANGE_CORDIRATOR: '/api/user/change_coordinator',
  GET_ALL_MY_MEETING: '/api/user/log',
  GET_ALL_MEETING_APPROVAL: '/api/meeting/approval_log',
  PATCH_APPROVAL_MEETING: '/api/meeting/admin/approve',
  DELETE_MEETING_BY_COORDIRATOR: '/api/meeting/delete',
  DELETE_MEETING_PERIODIC: 'api/meeting/periodic/delete',
  DELETE_MEETING_BY_ADMIN: '/api/meeting/admin/disapprove',
  SHEARCH_MEETING: '/api/meeting/search',
  EXPORT_XLS_FILE: '/api/location/export',
};
