"""Update is_approval on meeting table

Revision ID: 0a6e37e0f5f2
Revises: 6478a6d420bb
Create Date: 2019-09-26 16:24:58.281294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a6e37e0f5f2'
down_revision = '6478a6d420bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('manager_id', sa.Integer()))
    # op.execute('UPDATE location SET manager_id=9')
    # op.alter_column('location', 'manager_id', nullable=False)
    op.create_foreign_key('location_manager_id_fkey', 'location', 'user', ['manager_id'], ['id'], ondelete='CASCADE')
    op.add_column('meeting', sa.Column('is_approval', sa.Boolean(), nullable=True))
    op.add_column('meeting_user', sa.Column('note', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting_user', 'note')
    op.drop_column('meeting', 'is_approval')
    op.drop_constraint('location_manager_id_fkey', 'location', type_='foreignkey')
    op.drop_column('location', 'manager_id')
    # ### end Alembic commands ###
