"""Update. Update google calendar id and must synchronized on meeting table

Revision ID: 161bcc9a12fc
Revises: 7dbddf5e1e51
Create Date: 2019-08-26 14:44:00.683033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161bcc9a12fc'
down_revision = '7dbddf5e1e51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('google_calendar_id', sa.String(50), nullable=True))
    op.add_column('meeting', sa.Column('must_synchronized', sa.Boolean(), nullable=True))
    op.execute('UPDATE meeting SET must_synchronized=True')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting', 'must_synchronized')
    op.drop_column('meeting', 'google_calendar_id')
    # ### end Alembic commands ###
