"""Update google_calendar_id type on meeting table

Revision ID: 31a2bc07e93a
Revises: 161bcc9a12fc
Create Date: 2019-08-27 10:14:09.158051

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '31a2bc07e93a'
down_revision = '161bcc9a12fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meeting', 'google_calendar_id',
                    existing_type=sa.String(50),
                    type_=sa.String(length=50),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meeting', 'google_calendar_id',
                    existing_type=sa.String(length=50),
                    type_=sa.String(50),
                    existing_nullable=True)
    # ### end Alembic commands ###
