"""Add may join column on meeting user table

Revision ID: 7dbddf5e1e51
Revises: 5731606d5bd0
Create Date: 2019-08-19 09:43:08.978489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dbddf5e1e51'
down_revision = '5731606d5bd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting_user', sa.Column('may_join', sa.Boolean()))
    op.execute('UPDATE meeting_user SET may_join=false')
    op.alter_column('meeting_user', 'may_join', nullable=False)
    op.drop_constraint('role_user_user_id_fkey', 'role_user', type_='foreignkey')
    op.drop_constraint('role_user_role_id_fkey', 'role_user', type_='foreignkey')
    op.create_foreign_key('role_user_role_id_fkey', 'role_user', 'user', ['user_id'], ['id'])
    op.create_foreign_key('role_user_user_id_fkey', 'role_user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('role_user_user_id_fkey', 'role_user', type_='foreignkey')
    op.drop_constraint('role_user_role_id_fkey', 'role_user', type_='foreignkey')
    op.create_foreign_key('role_user_role_id_fkey', 'role_user', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('role_user_user_id_fkey', 'role_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('meeting_user', 'may_join')
    # ### end Alembic commands ###
