"""Update need_appoval on location table

Revision ID: c2d4469ade1e
Revises: cadca62e4667
Create Date: 2019-10-21 23:15:33.378984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2d4469ade1e'
down_revision = 'cadca62e4667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('need_approval', sa.Boolean(), nullable=True))
    op.execute('UPDATE location SET need_approval=true')
    op.alter_column('location', 'need_approval', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('location', 'need_approval', nullable=True)
    op.drop_column('location', 'need_approval')
    # ### end Alembic commands ###
