"""add may_join on meeting_user table

Revision ID: cadca62e4667
Revises: cb63f44f8d8b
Create Date: 2019-09-26 17:16:00.098910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cadca62e4667'
down_revision = 'cb63f44f8d8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting_user', sa.Column('may_join', sa.Boolean()))
    op.execute('UPDATE meeting_user SET may_join=True')
    op.alter_column('meeting_user', 'may_join', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting_user', 'may_join')
    # ### end Alembic commands ###
