"""add is_response on meeting_user table

Revision ID: cb63f44f8d8b
Revises: 0a6e37e0f5f2
Create Date: 2019-09-26 16:35:28.690377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb63f44f8d8b'
down_revision = '0a6e37e0f5f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting_user', sa.Column('is_response', sa.Boolean()))
    op.execute('UPDATE meeting_user SET is_response=true')
    op.alter_column('meeting_user', 'is_response', nullable=False)
    op.drop_column('meeting_user', 'may_join')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting_user', sa.Column('may_join', sa.BOOLEAN()))
    op.execute('UPDATE meeting_user SET may_join=false')
    op.alter_column('meeting_user', 'may_join', nullable=False)
    op.drop_column('meeting_user', 'is_response')
    # ### end Alembic commands ###
